#!/usr/bin/env bash

source "$(dirname $0)/../common/functions"
source "$(dirname $0)/vars"

function verify_max_args() {
	local MAX_ARGS="$1"
	[[ $# -le $((MAX_ARGS+1)) ]] || fail "Invalid number of arguments ($(($#-1)), expected $MAX_ARGS)."
}

case "$1" in
	nginx:cache:enable)
		verify_app_name "$2"
		verify_max_args 2 "$@"

		mkdir -p $CACHE_DIR
		echo Enabled Nginx proxy cache for $APP

		dokku ps:restart "$APP"
		;;

	nginx:cache:disable)
		verify_app_name "$2"
		verify_max_args 2 "$@"

		rm -rf $DOKKU_ROOT/$APP/NGINX_CACHE
		echo Disabled Nginx proxy cache for $APP

		dokku ps:restart "$APP"
		;;

	help | nginx:help | nginx:cache:help)
		cat && cat <<-EOF
		    nginx:cache:enable <app>                Enable Nginx proxy cache for an app
		    nginx:cache:disable <app>               Disable Nginx proxy cache for an app
		EOF
		;;

	*)
		exit $DOKKU_NOT_IMPLEMENTED_EXIT
		;;
esac
